
package com.sml.eplatform.inplant.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import net.java.dev.jaxb.array.ObjectFactory;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EOrderInfoExtraction", targetNamespace = "http://webservice.inplant.eplatform.sml.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EOrderInfoExtraction {


    /**
     * 
     * @param actionType
     * @param password
     * @param loginId
     * @param remoteIPAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String login(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "remoteIPAddress", partName = "remoteIPAddress")
        String remoteIPAddress,
        @WebParam(name = "actionType", partName = "actionType")
        String actionType);

    /**
     * 
     * @param prodCode
     * @param password
     * @param callout
     * @param createDateTo
     * @param loginId
     * @param custPo
     * @param createDateFrom
     * @param eorderId
     * @param epc
     * @param subProgramId
     * @param programId
     * @param woNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String queryOrder(
        @WebParam(name = "programId", partName = "programId")
        String programId,
        @WebParam(name = "subProgramId", partName = "subProgramId")
        String subProgramId,
        @WebParam(name = "eorderId", partName = "eorderId")
        String eorderId,
        @WebParam(name = "custPo", partName = "custPo")
        String custPo,
        @WebParam(name = "callout", partName = "callout")
        String callout,
        @WebParam(name = "prodCode", partName = "prodCode")
        String prodCode,
        @WebParam(name = "createDateFrom", partName = "createDateFrom")
        String createDateFrom,
        @WebParam(name = "createDateTo", partName = "createDateTo")
        String createDateTo,
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "epc", partName = "epc")
        String epc,
        @WebParam(name = "woNo", partName = "woNo")
        String woNo);

    /**
     * 
     * @param password
     * @param loginId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getPrintOrderWorkOrderStatusListValue(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param loginId
     * @param createDateTo
     * @param createDateFrom
     * @param printOrderNo
     * @param custItemCode
     * @param start
     * @param custName
     * @param custCode
     * @param password
     * @param productCode
     * @param orderStatusId
     * @param limit
     * @param style
     * @param subProgramId
     * @param programId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String retrievePrintedQtyVsActualQtyRptData(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "programId", partName = "programId")
        String programId,
        @WebParam(name = "subProgramId", partName = "subProgramId")
        String subProgramId,
        @WebParam(name = "custItemCode", partName = "custItemCode")
        String custItemCode,
        @WebParam(name = "productCode", partName = "productCode")
        String productCode,
        @WebParam(name = "style", partName = "style")
        String style,
        @WebParam(name = "createDateFrom", partName = "createDateFrom")
        String createDateFrom,
        @WebParam(name = "createDateTo", partName = "createDateTo")
        String createDateTo,
        @WebParam(name = "printOrderNo", partName = "printOrderNo")
        String printOrderNo,
        @WebParam(name = "orderStatusId", partName = "orderStatusId")
        String orderStatusId,
        @WebParam(name = "custCode", partName = "custCode")
        String custCode,
        @WebParam(name = "custName", partName = "custName")
        String custName,
        @WebParam(name = "start", partName = "start")
        String start,
        @WebParam(name = "limit", partName = "limit")
        String limit);

    /**
     * 
     * @param user
     * @param passphase
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getSFtpInfo(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "passphase", partName = "passphase")
        String passphase);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getMainProgramList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getSalesOrderStatusList();

    /**
     * 
     * @param user
     * @param passphase
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getSFtpUploadInfo(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "passphase", partName = "passphase")
        String passphase);

    /**
     * 
     * @param programId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getSubProgramList(
        @WebParam(name = "programId", partName = "programId")
        String programId);

    /**
     * 
     * @param password
     * @param fileByte
     * @param erpSoNumber
     * @param userId
     * @param fileType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String uploadPROFileByWorkOrderId(
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "erpSoNumber", partName = "erpSoNumber")
        String erpSoNumber,
        @WebParam(name = "fileType", partName = "fileType")
        String fileType,
        @WebParam(name = "fileByte", partName = "fileByte")
        byte[] fileByte);

    /**
     * 
     * @param workOrderNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getSKUInPlantDisplay(
        @WebParam(name = "work_order_number", partName = "work_order_number")
        String workOrderNumber);

    /**
     * 
     * @param password
     * @param loginId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getPrinterListValue(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param loginId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getUserInformation(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId);

    /**
     * 
     * @param password
     * @param loginId
     * @param retagXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String processRfidRetagging(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "retag_xml", partName = "retag_xml")
        String retagXml);

    /**
     * 
     * @param loginId
     * @param custItemCode
     * @param start
     * @param custName
     * @param custCode
     * @param password
     * @param productCode
     * @param selectedMonth
     * @param selectedYear
     * @param limit
     * @param style
     * @param subProgramId
     * @param programId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String retrieveCustomerUsageRptData(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "programId", partName = "programId")
        String programId,
        @WebParam(name = "subProgramId", partName = "subProgramId")
        String subProgramId,
        @WebParam(name = "custItemCode", partName = "custItemCode")
        String custItemCode,
        @WebParam(name = "productCode", partName = "productCode")
        String productCode,
        @WebParam(name = "style", partName = "style")
        String style,
        @WebParam(name = "selectedYear", partName = "selectedYear")
        String selectedYear,
        @WebParam(name = "selectedMonth", partName = "selectedMonth")
        String selectedMonth,
        @WebParam(name = "custCode", partName = "custCode")
        String custCode,
        @WebParam(name = "custName", partName = "custName")
        String custName,
        @WebParam(name = "start", partName = "start")
        String start,
        @WebParam(name = "limit", partName = "limit")
        String limit);

    /**
     * 
     * @param handlingCompanyId
     * @param password
     * @param loginId
     * @param productCode
     * @param createDateTo
     * @param createDateFrom
     * @param start
     * @param limit
     * @param subProgramId
     * @param custName
     * @param custCode
     * @param programId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String retrieveConsumerableUsageRptData(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "programId", partName = "programId")
        String programId,
        @WebParam(name = "subProgramId", partName = "subProgramId")
        String subProgramId,
        @WebParam(name = "productCode", partName = "productCode")
        String productCode,
        @WebParam(name = "handlingCompanyId", partName = "handlingCompanyId")
        String handlingCompanyId,
        @WebParam(name = "createDateFrom", partName = "createDateFrom")
        String createDateFrom,
        @WebParam(name = "createDateTo", partName = "createDateTo")
        String createDateTo,
        @WebParam(name = "custCode", partName = "custCode")
        String custCode,
        @WebParam(name = "custName", partName = "custName")
        String custName,
        @WebParam(name = "start", partName = "start")
        String start,
        @WebParam(name = "limit", partName = "limit")
        String limit);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getHandlingCompany();

    /**
     * 
     * @param prodCode
     * @param password
     * @param callout
     * @param createDateTo
     * @param loginId
     * @param custPo
     * @param createDateFrom
     * @param eorderId
     * @param epc
     * @param subProgramId
     * @param programId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getEOrderInfo(
        @WebParam(name = "programId", partName = "programId")
        String programId,
        @WebParam(name = "subProgramId", partName = "subProgramId")
        String subProgramId,
        @WebParam(name = "eorderId", partName = "eorderId")
        String eorderId,
        @WebParam(name = "custPo", partName = "custPo")
        String custPo,
        @WebParam(name = "callout", partName = "callout")
        String callout,
        @WebParam(name = "prodCode", partName = "prodCode")
        String prodCode,
        @WebParam(name = "createDateFrom", partName = "createDateFrom")
        String createDateFrom,
        @WebParam(name = "createDateTo", partName = "createDateTo")
        String createDateTo,
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "epc", partName = "epc")
        String epc);

    /**
     * 
     * @param programId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean isSpecialProgram(
        @WebParam(name = "programId", partName = "programId")
        String programId);

    /**
     * 
     * @param password
     * @param arg5
     * @param erpSoNumber
     * @param userId
     * @param downloadedWorkOrderIds
     * @param arg6
     * @param fileType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getEOrderPROFile(
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "erpSoNumber", partName = "erpSoNumber")
        String erpSoNumber,
        @WebParam(name = "fileType", partName = "fileType")
        String fileType,
        @WebParam(name = "downloadedWorkOrderIds", partName = "downloadedWorkOrderIds")
        StringArray downloadedWorkOrderIds,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     * @param user
     * @param passphase
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getAdvanceLogin(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "passphase", partName = "passphase")
        String passphase);

    /**
     * 
     * @param password
     * @param printedResult
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String uploadPROFile(
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "printedResult", partName = "printedResult")
        String printedResult);

    /**
     * 
     * @param password
     * @param loginId
     * @param subProgramCode
     * @param subProgramId
     * @param locale
     * @param captionKeys
     * @param mainProgramCode
     * @param mainProgramId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getCaption(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "caption_keys", partName = "caption_keys")
        StringArray captionKeys,
        @WebParam(name = "locale", partName = "locale")
        String locale,
        @WebParam(name = "main_program_id", partName = "main_program_id")
        String mainProgramId,
        @WebParam(name = "main_program_code", partName = "main_program_code")
        String mainProgramCode,
        @WebParam(name = "sub_program_id", partName = "sub_program_id")
        String subProgramId,
        @WebParam(name = "sub_program_code", partName = "sub_program_code")
        String subProgramCode);

    /**
     * 
     * @param actionType
     * @param password
     * @param loginId
     * @param remoteIPAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String loginEpv(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "remoteIPAddress", partName = "remoteIPAddress")
        String remoteIPAddress,
        @WebParam(name = "actionType", partName = "actionType")
        String actionType);

    /**
     * 
     * @param prodCode
     * @param password
     * @param loginId
     * @param productionCompanyCode
     * @param styleNo
     * @param customerId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getLatestJob(
        @WebParam(name = "prodCode", partName = "prodCode")
        String prodCode,
        @WebParam(name = "styleNo", partName = "styleNo")
        String styleNo,
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "productionCompanyCode", partName = "productionCompanyCode")
        String productionCompanyCode,
        @WebParam(name = "customerId", partName = "customerId")
        String customerId);

    /**
     * 
     * @param password
     * @param loginId
     * @param formatXmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getFormatData(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "formatXmlStr", partName = "formatXmlStr")
        String formatXmlStr);

    /**
     * 
     * @param password
     * @param loginId
     * @param jccXmlStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getJccData(
        @WebParam(name = "loginId", partName = "loginId")
        String loginId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "jccXmlStr", partName = "jccXmlStr")
        String jccXmlStr);

}
