
package com.sml.eplatform.inplant.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EOrderInfoExtractionImplService", targetNamespace = "http://webservice.inplant.eplatform.sml.com/", wsdlLocation = "http://localhost:8080/leoEp/InPlantPrintWs?wsdl")
public class EOrderInfoExtractionImplService
    extends Service
{

    private final static URL EORDERINFOEXTRACTIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EORDERINFOEXTRACTIONIMPLSERVICE_EXCEPTION;
    private final static QName EORDERINFOEXTRACTIONIMPLSERVICE_QNAME = new QName("http://webservice.inplant.eplatform.sml.com/", "EOrderInfoExtractionImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/leoEp/InPlantPrintWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EORDERINFOEXTRACTIONIMPLSERVICE_WSDL_LOCATION = url;
        EORDERINFOEXTRACTIONIMPLSERVICE_EXCEPTION = e;
    }

    public EOrderInfoExtractionImplService() {
        super(__getWsdlLocation(), EORDERINFOEXTRACTIONIMPLSERVICE_QNAME);
    }

    public EOrderInfoExtractionImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EORDERINFOEXTRACTIONIMPLSERVICE_QNAME, features);
    }

    public EOrderInfoExtractionImplService(URL wsdlLocation) {
        super(wsdlLocation, EORDERINFOEXTRACTIONIMPLSERVICE_QNAME);
    }

    public EOrderInfoExtractionImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EORDERINFOEXTRACTIONIMPLSERVICE_QNAME, features);
    }

    public EOrderInfoExtractionImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EOrderInfoExtractionImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EOrderInfoExtraction
     */
    @WebEndpoint(name = "EOrderInfoExtractionImplPort")
    public EOrderInfoExtraction getEOrderInfoExtractionImplPort() {
        return super.getPort(new QName("http://webservice.inplant.eplatform.sml.com/", "EOrderInfoExtractionImplPort"), EOrderInfoExtraction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EOrderInfoExtraction
     */
    @WebEndpoint(name = "EOrderInfoExtractionImplPort")
    public EOrderInfoExtraction getEOrderInfoExtractionImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.inplant.eplatform.sml.com/", "EOrderInfoExtractionImplPort"), EOrderInfoExtraction.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EORDERINFOEXTRACTIONIMPLSERVICE_EXCEPTION!= null) {
            throw EORDERINFOEXTRACTIONIMPLSERVICE_EXCEPTION;
        }
        return EORDERINFOEXTRACTIONIMPLSERVICE_WSDL_LOCATION;
    }

}
